# Generated by Django 3.0.5 on 2020-04-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TescoProducts',
            fields=[
                ('image_link', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('product_link', models.CharField(blank=True, max_length=500, null=True)),
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
