# Generated by Django 3.0.5 on 2020-05-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleVelocity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('sessions', models.IntegerField()),
                ('session_percentage', models.DecimalField(decimal_places=10, max_digits=19)),
                ('page_views', models.IntegerField()),
                ('page_views_percentage', models.DecimalField(decimal_places=10, max_digits=19)),
                ('buy_box_percentage', models.DecimalField(decimal_places=10, max_digits=19)),
                ('units_ordered', models.IntegerField()),
                ('units_ordered_b2b', models.IntegerField()),
                ('unit_session_percentage', models.DecimalField(decimal_places=10, max_digits=19)),
                ('unit_session_percentage_b2b', models.DecimalField(decimal_places=10, max_digits=19)),
                ('ordered_product_sales', models.DecimalField(decimal_places=10, max_digits=19)),
                ('ordered_product_sales_b2b', models.DecimalField(decimal_places=10, max_digits=19)),
                ('total_order_items', models.IntegerField()),
                ('total_order_items_b2b', models.IntegerField()),
                ('average_selling_price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('sales_velocity', models.DecimalField(decimal_places=10, max_digits=19)),
                ('days', models.IntegerField()),
            ],
        ),
    ]
