# Generated by Django 3.0.5 on 2020-05-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salevelocity', '0002_salevelocity_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salevelocity',
            name='datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
