# Generated by Django 3.0.5 on 2020-04-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(blank=True, max_length=500, null=True)),
                ('brand', models.CharField(blank=True, max_length=500, null=True)),
                ('datetime', models.CharField(blank=True, max_length=500, null=True)),
                ('image_link', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('product_link', models.CharField(blank=True, max_length=500, null=True)),
                ('rank1', models.CharField(blank=True, max_length=500, null=True)),
                ('rank2', models.CharField(blank=True, max_length=500, null=True)),
                ('ratings', models.CharField(blank=True, max_length=500, null=True)),
                ('stars', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
