# Generated by Django 3.0.5 on 2020-04-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seller_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
