# Generated by Django 3.0.5 on 2020-04-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_brand_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
