# Generated by Django 3.0.5 on 2020-04-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productskeeps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsKeeps',
            new_name='ProductsKeepa',
        ),
    ]
