# Generated by Django 3.0.5 on 2020-04-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200418_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='rank1',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='rank2',
            new_name='reviews',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stars',
        ),
    ]
