# Generated by Django 3.0.5 on 2020-04-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200418_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='ratings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='reviews',
            field=models.IntegerField(null=True),
        ),
    ]
