# Generated by Django 3.0.5 on 2020-04-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200418_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
