# Generated by Django 3.0.5 on 2020-04-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200424_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ratings',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
